name: 'Unit Test'
description: 'Run unit tests'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: npm ci
    - name: Run test
      shell: bash
      run: npm run test
