name: 'Lint'
description: 'Run eslint'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: npm ci
    - name: Run lint
      shell: bash
      run: npm run lint
